export * from './TGHArtColl';
export * from './TGHArtCollGallery';
export * from './TGHArtCollHero';
export * from './TGHButton';
export * from './TGHCalendar';
export * from './TGHComboBox';
export * from './TGHComfort';
export * from './TGHDining';
export * from './TGHDiningSection01';
export * from './TGHDiningSection02';
export * from './TGHDiningSection03';
export * from './TGHDrawer';
export * from './TGHExperience';
export * from './TGHExperienceImage';
export * from './TGHGallery';
export * from './TGHGalleryImages';
// export * from './TGHHotelDescription';
// export * from './TGHHotelFeatures';
export * from './TGHHotelHero';
// export * from './TGHHotelNotice';
// export * from './TGHHotelVisual';
export * from './TGHIcon';
export * from './TGHOF';
export * from './TGHOFImage';
export * from './TGHOFSection01';
export * from './TGHOFSection02';
export * from './TGHOFSection03';
export * from './TGHRooms';
export * from './TGHRoomsImage';
export * from './TGHRoomsText';
export * from './TGHSearchInfoForm';
